### ISSUE TITLE
symbol of superroute drawn twice - bug?

### ISSUE THREAD

**Issue by Hufkratzer** [lonvia/waymarked-trails-site#220]
On the map http://riding.waymarkedtrails.org/de/?zoom=13&lat=52.21175&lon=12.38403&hill=0#
you see 2 routes that are part of the same superroute and partially follow the same track. In this part the symbol of the superroute (green sqare, foreground symbol missing) is drawn twice. I see no reason why the symbol is drawn twice, perhaps it is a bug that can be fixed.

In real life the sign post at this place looks like this:
![cimg4073](https://cloud.githubusercontent.com/assets/5958184/10268911/f416024e-6ac6-11e5-95a0-aabc3f7eac84.JPG)

**Comment by lonvia** [comment]
Yes, the symbol is drawn twice because both containing routes share the same way. I'm tempted to call this a feature because your superroute is quite obviously not a route anymore but a collection of routes. I think you what you meant to tag is: `type=network`

**Comment by Hufkratzer** [comment]
Yes, it was not a real superroute. I did that because I saw a similar thing somewhere else. I have changed the relation to type network and the green squares (most) disappeared. Great feature too!

Will you support networks? Is type network something official now or just a proposal? (see http://wiki.openstreetmap.org/wiki/Types_of_relation / http://wiki.openstreetmap.org/wiki/Relations/Proposed/Network )

**Comment by lonvia** [comment]
I'm not sure about supporting network relations. On one side I have strong feelings about [not using relations as categories](http://wiki.openstreetmap.org/wiki/Relations/Relations_are_not_Categories), i.e. I would prefer if we had just a tag for network names that could be added to each relation. Much easier to process, too. On the other hand, I prefer supporting network relations over people misusing the type=route just to have their network visible on the map.

Closing this issue here, as I don't think I will remove duplicates from superroutes but feel free to open a new feature request for networks and I'll think some more about it.
