### ISSUE TITLE
osmc:symbol vs ktc_color

### ISSUE THREAD

**Issue by royas** [lonvia/waymarked-trails-site#257]
I think that osmc:symbol should take precedence over ktc_<color>=<type>. The first one allows to describe more specific symbol.  Eg. theres learning path with custom symbol, which is described with osmc:symbol, but it also has ktc_blue=learning, which causes just simple "slash on square".

**Comment by lonvia** [comment]
I'm rather reluctant to do that  because the kct_* symbols are specially designed for the purpose and are therefore much nicer than the stuff that is created on the fly for osmc:symbol. 

Checking the database, there are no more specific osmc:symbols for kct_blue=learning. There are a couple of them for kct_green=learning. So how much of a problem is that actually?

**Comment by lonvia** [comment]
Closing for lack of response.
